version: "3.9"
name: tiros
services:
  kubo:
    image: ipfs/kubo:v0.38.0
    environment:
      - IPFS_TELEMETRY=off
    ports:
      - "0.0.0.0:4001:4001/tcp"
      - "0.0.0.0:4001:4001/udp"
      - "0.0.0.0:5001:5001"
      - "0.0.0.0:8080:8080"
  chrome:
    image: browserless/chrome:latest
    ports:
      - "3000:3000"
